#!bin/bash

if [ $# -ne 2 ]
then
        echo "2 arguments are needed, directory being moved and target directory"
fi

#check if directory exists
if [ ! -d $1 ]
then
        echo "Error! $1 does not exit or not a directory
fi

#check if target directory exists
if [ ! -d $2 ]
then
        echo "Error! $2 does not exit or not a directory
fi

#delete only if directory copied successfully
cp -r $1 $2 && rm -rf $1
echo "Directory $1 was successfully moved to $2"
