#!/bin/bash
read -p "Please enter username: " username
if [ "$username" = "*******" ]
thhen
          read -p "Please enter password: " password
          if [ "$password" = "*******" ]
          then
                  echo "Welcome, $username!"
          else
                  echo "Invalid password!"
                  exit 1
          fi
else 
          echo "Invalid username!"
fi
